import Head from 'next/head'
import { useEffect, useState } from 'react'
import { useRaffleContract } from '../context/ContractContext'
import { useWallet } from '../context/WalletContext'
import styles from '../styles/Home.module.css'

export default function Home() {
    const { isStartingUp, isAuthenticated, signIn, signOut, userId } = useWallet()
    const { getRaffleList, createRaffle } = useRaffleContract()
    const [ raggleList, setRaffleList ] = useState({})
    const [ formData, setFormData ] = useState({
        min_entry_price:1,
        min_participants:1,
        prize:"test_hash",
        description: "test_hash",
        nft_account: "test_hash",
        open_days:1,
    })

    useEffect(() => {
        if (!isStartingUp) {
            getRaffleList().then((data) => {
                setRaffleList(data)
            })
            .catch((error) => {
                console.error(error)
            })
        }
    },[isStartingUp])

    const handleLogin = () => {
        signIn()
    }

    const handleSignout = () => {
        signOut()
    }

    const handleCreateRaffle = (e) => {
        e.preventDefault()
        const createRaffleArgs = {
            description: "test raffle",
            min_entry_price: formData.min_entry_price,
            min_participants: formData.min_participants,
            prize: formData.prize,
            nft_account: "",
            open_days: 1,
        }
        createRaffle(createRaffleArgs)
        .then((data) => {
            console.log(data)
        })
        .catch((error) => {
            console.error(error)
        })
    }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a>dRaffleApp!</a>
        </h1>

        {
            isStartingUp ? (
                <p className={styles.description} >
                    Loading ...
                </p>
            ) : !isAuthenticated ? (
                <button onClick={handleLogin}>
                    <p className={styles.description} >
                        Wallet Login
                    </p>
                </button>
            ) : (
                <>
                    <p className={styles.description} >
                        Hola tu accountId es: {userId}
                    </p>
                    <form style={{diplay: "flex", flexDirection:"column"}}>
                        <div>
                            <label>
                                min_entry_price:
                                <input type="number" value={formData.min_entry_price} onChange={(e) => setFormData((prev) => ({...prev, min_entry_price: e.target.value}))}/>
                            </label>
                        </div>
                        <div>
                            <label>
                                min_participants:
                                <input type="number" value={formData.min_participants} onChange={(e) => setFormData((prev) => ({...prev, min_participants: e.target.value}))}/>
                            </label>
                        </div>
                        <div>
                            <label>
                                prize (nft hash):
                                <input type="text" placeholder="NFT hash" value={formData.prize} onChange={(e) => setFormData((prev) => ({...prev, prize: e.target.value}))}/>
                            </label>
                        </div>
                        <div>
                            <label>
                                description:
                                <input type="text" placeholder="description" value={formData.description} onChange={(e) => setFormData((prev) => ({...prev, description: e.target.value}))}/>
                            </label>
                        </div>
                        <div>
                            <label>
                                nft_account:
                                <input type="text" placeholder="nft_account" value={formData.nft_account} onChange={(e) => setFormData((prev) => ({...prev, nft_account: e.target.value}))}/>
                            </label>
                        </div>
                        <div>
                            <label>
                                open_days:
                                <input type="number" value={formData.open_days} onChange={(e) => setFormData((prev) => ({...prev, open_days: e.target.value}))}/>
                            </label>
                        </div>
                        <button onClick={handleCreateRaffle}>
                            Create raffle
                        </button>
                    </form>
                </>
            )
        }
        <div className={styles.description}>
            <p>Lista de raffles</p>
            <p>{JSON.stringify(raggleList)}</p>
        </div>
        {
            !isStartingUp && isAuthenticated && (
                <button onClick={handleSignout}>
                    Sign out
                </button>
            )
        }
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Grupo 4 - Platzi Near Developer Program
        </a>
      </footer>
    </div>
  )
}
